#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Get the PID of the 4-to_infinity_and_beyond process
PID=$(pgrep -f 4-to_infinity_and_beyond)

# Check if the process is running
if [ -n "$PID" ]; then
  kill "$PID"
  echo "4-to_infinity_and_beyond process has been terminated."
else
  echo "4-to_infinity_and_beyond process not found."
fi

