#!/usr/bin/env bash
# Bash script to display username, user ID, and home directory path from /etc/passwd

# Read /etc/passwd line by line using while loop
input="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done < "$input"

