#!/usr/bin/env bash
# This script displays "Best School" 10 times, with "Hi" on a new line on the 9th iteration

# Initialize a counter
counter=0

# Using a while loop to print "Best School" 10 times
while [ $counter -lt 10 ]; do
    if [ $counter -eq 8 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done

