#!/usr/bin/env bash
# This script displays time in a 12-hour format with hours from 0 to 12 and minutes from 1 to 59

# Initialize variables
i="0"
while [ $i -le 12 ]
do
echo "Hour: $i"
j="1"
while [ $j -le 59 ]
do
echo "$j"
j=$((j+1))
done
i=$((i+1))
done
