#!/usr/bin/env bash
# This script displays time in a 12-hour format with hours from 0 to 12 and minutes from 1 to 59

# Initialize variables
hour=0
minute=1

# Using a while loop to display time
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    while [ $minute -le 59 ]; do
        echo $minute
        ((minute++))
    done
    ((hour++))
    minute=1  # Reset minute for the next hour
done

