#!/usr/bin/env bash
# This script configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8

cp /etc/hosts /etc/hosts.bak
{
    echo "127.0.0.2 localhost"
    echo "8.8.8.8 facebook.com"
} >> /etc/hosts

